name: portal

networks:
    frontend:
        driver: ${NETWORKS_DRIVER}

services:
    #### User service ###########################################
    api_gateway:
        container_name: zkit_api_gateway
        build:
            context: ./api_gateway
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        env_file:
            - .env
        command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
        ports:
            - "${APP_PORT}:8000"
        volumes:
            - ./api_gateway/src/:/zkit/
        networks:
            - frontend
        depends_on:
            - engine
        restart: unless-stopped

    ### User service ###########################################
    engine:
        container_name: zkit_engine
        build:
            context: ./engine
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        env_file:
            - .env
        command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
        ports:
            - "${USER_APP_PORT}:8000"
        volumes:
            - ./engine/src/:/zkit/
        networks:
            - frontend
        depends_on:
            - postgres
            - avatar
            - ecommerce
            - content
            - multimedia
        restart: unless-stopped

    ## Avatar #################################################
    avatar:
        container_name: zkit_avatar
        build:
            context: ./avatar
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
                - INSTALL_FFMPEG=${INSTALL_FFMPEG}
        env_file:
            - .env
        command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
        ports:
            - "${AVATAR_APP_PORT}:8000"
        volumes:
            - ./avatar/src/:/zkit/
        networks:
            - frontend
        restart: unless-stopped

    ### ecommerce service #########################################
    ecommerce:
        container_name: zkit_ecommerce
        build:
            context: ./ecommerce
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        env_file:
            - .env
        command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
        ports:
            - "${ECOMMERCE_APP_PORT}:8000"
        volumes:
            - ./ecommerce/src/:/zkit/
        networks:
            - frontend
        restart: unless-stopped

    ### multimedia service #########################################
    multimedia:
        container_name: zkit_multimedia
        build:
            context: ./multimedia
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        env_file:
            - .env
        command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
        ports:
            - "${MULTIMEDIA_APP_PORT}:8000"
        volumes:
            - ./multimedia/src/:/zkit/
        networks:
            - frontend
        restart: unless-stopped

    ### content service ###########################################
    content:
        container_name: zkit_content
        build:
            context: ./content
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        env_file:
            - .env
        command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
        ports:
            - "${CONTENT_APP_PORT}:8000"
        volumes:
            - ./content/src/:/zkit/
        networks:
            - frontend
        depends_on:
            - mongo
        restart: unless-stopped

    ### Postgres DB #########################################
    postgres:
        container_name: zkit_postgres
        build:
            context: ./containers/postgres
            args:
                - POSTGRES_VERSION=${POSTGRES_VERSION}
        volumes:
            - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-dbname}
            POSTGRES_USER: ${POSTGRES_USER:-username}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            PGDATA: /var/lib/postgresql/data/
        ports:
            - "${POSTGRES_PORT}:5432"
        networks:
            - frontend
        depends_on:
            - pgadmin
        restart: unless-stopped

    ### pgAdmin ##############################################
    pgadmin:
        container_name: zkit_pgadmin
        build:
            context: ./containers/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-info@info.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
        volumes:
            - ${DATA_PATH_HOST}/pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - frontend
        restart: unless-stopped

    ### mongo DB #########################################
    mongo:
        container_name: zkit_mongo
        build:
            context: ./containers/mongo
            args:
                - MONGO_VERSION=${MONGO_VERSION}
        restart: unless-stopped
        volumes:
            - ${DATA_PATH_HOST}/mongodb:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        ports:
            - ${MONGO_PORT}:27017
        networks:
            - frontend

volumes:
    postgres:
        driver: ${VOLUMES_DRIVER}
    pgadmin:
        driver: ${VOLUMES_DRIVER}
    mongo:
        driver: ${VOLUMES_DRIVER}
