services:
    network_management:
        #container_name: zkit_content
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        env_file:
            - ./../.env
        ports:
            - "8082:8000"
        volumes:
            - ./src/:/zkit/
        networks:
            - frontend
        depends_on:
            - mongo
        restart: unless-stopped
